#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "InitInfra · fejlesztői környezet (ROADMAP 0.2–0.4)"

# ── 1. WSL2 ───────────────────────────────────────────────────────────────
stage "WSL2 · Ubuntu 24.04"
say "Opcionális: kényelmi Linux shell. A VM-hez nem kell — oda ssh-val vagy"
  say "multipass shell-lel mész, a kód pedig git push/pull úton jut oda."
if wsl.exe -l -q 2>/dev/null | tr -d '\r\0' | grep -qi 'Ubuntu-24.04'; then
  say "${GREEN}✓${RESET} Ubuntu-24.04 már telepítve van a WSL-be."
else
  warn "Nincs Ubuntu-24.04 a WSL alatt."
  step "Nyiss egy PowerShellt RENDSZERGAZDAKÉNT, és futtasd:"
  note "      wsl --install -d Ubuntu-24.04"
  step "Ha újraindítást kér, indítsd újra a gépet."
  step "Első indításkor kér egy felhasználónevet és jelszót — add meg."
  pause "Enter, ha a telepítés lefutott (vagy ha most kihagynád)."
fi

# ── 2. Multipass ──────────────────────────────────────────────────────────
stage "Multipass"
say "Ez hozza létre az eldobható Ubuntu VM-et, Hyper-V-re épülve."
if command -v multipass >/dev/null 2>&1; then
  say "${GREEN}✓${RESET} $(multipass version 2>/dev/null | head -n1)"
else
  open_url "https://multipass.run/install"
  step "Töltsd le és telepítsd a Windows verziót."
  step "Ha a telepítő Hyper-V engedélyezését kéri, engedd — és indítsd újra a gépet."
  note "Alternatíva: Hyper-V Managerből kézzel is készíthetsz Ubuntu 24.04 VM-et,"
  note "de akkor a 3. szakaszt is kézzel kell elvégezned."
  pause "Enter, ha a multipass telepítve van."
  if ! command -v multipass >/dev/null 2>&1; then
    warn "A multipass még mindig nem érhető el ebből a shellből."
    note "Nyiss egy ÚJ Git Bash ablakot (hogy frissüljön a PATH), és futtasd újra ezt a scriptet."
    SKIPPED+=("Multipass telepítés — a VM létrehozása kimaradt")
  fi
fi

# ── 3. Az eldobható VM ────────────────────────────────────────────────────
stage "Az eldobható VM"
say "Ez lesz a célgép. Az arany szabály: ha valami elromlik, eldobod és újra létrehozod."
if ! command -v multipass >/dev/null 2>&1; then
  warn "Multipass nélkül ezt a szakaszt kihagyjuk."
else
  ask VM_NAME "A VM neve [infra]:"
  [[ -z "${VM_NAME:-}" ]] && VM_NAME="infra"

  if multipass info "$VM_NAME" >/dev/null 2>&1; then
    say "${GREEN}✓${RESET} A(z) $VM_NAME VM már létezik."
  else
    say "Létrehozás: Ubuntu 24.04, 4 mag, 8 GB RAM, 40 GB lemez. Ez pár percig tart."
    multipass launch 24.04 --name "$VM_NAME" --cpus 4 --memory 8G --disk 40G
  fi

  VM_IP=$(multipass info "$VM_NAME" | awk '/^IPv4/ {print $2; exit}')
  if [[ -z "${VM_IP:-}" ]]; then
    warn "Nem sikerült kiolvasni a VM IP-jét."
    SKIPPED+=("VM IP kiolvasása — nézd meg: multipass info $VM_NAME")
  else
    say "A VM címe: ${BOLD}$VM_IP${RESET}"

    SSH_KEY="$HOME/.ssh/id_ed25519"
    if [[ ! -f "$SSH_KEY.pub" ]]; then
      say "Nincs ed25519 SSH kulcsod, generálok egyet (jelszó nélkül)."
      ssh-keygen -t ed25519 -N "" -f "$SSH_KEY" -C "initinfra-dev"
    fi
    PUBKEY=$(cat "$SSH_KEY.pub")

    say "SSH kulcs feltöltése a VM-re..."
    multipass exec "$VM_NAME" -- bash -c \
      "mkdir -p ~/.ssh && chmod 700 ~/.ssh && touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && grep -qxF '$PUBKEY' ~/.ssh/authorized_keys || echo '$PUBKEY' >> ~/.ssh/authorized_keys"

    if ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10 \
         -i "$SSH_KEY" "ubuntu@$VM_IP" true 2>/dev/null; then
      say "${GREEN}✓${RESET} ssh ubuntu@$VM_IP működik."
    else
      warn "Az SSH próba nem sikerült — próbáld kézzel: ssh ubuntu@$VM_IP"
      SKIPPED+=("SSH hozzáférés a VM-hez")
    fi

    write_env VM_NAME "$VM_NAME"
    write_env VM_IP "$VM_IP"
  fi
fi

# ── 4. GitHub repo ────────────────────────────────────────────────────────
stage "GitHub repo"
say "A 8. fázis 'curl | bash' tesztje csak akkor működik, ha a repo elérhető GitHubról."
if ! command -v gh >/dev/null 2>&1; then
  warn "A gh CLI nincs telepítve."
  open_url "https://cli.github.com/"
  SKIPPED+=("GitHub repo létrehozása — előbb telepítsd a gh CLI-t")
else
  if gh auth status >/dev/null 2>&1; then
    say "${GREEN}✓${RESET} Már be vagy jelentkezve a GitHubra."
  else
    step "Most elindul a 'gh auth login'. Válaszd: GitHub.com → HTTPS → böngészős belépés."
    pause "Enter a folytatáshoz."
    gh auth login || true
  fi

  if ! gh auth status >/dev/null 2>&1; then
    SKIPPED+=("GitHub bejelentkezés — futtasd később: gh auth login")
  else
    if git remote get-url origin >/dev/null 2>&1; then
      say "${GREEN}✓${RESET} Az origin remote már be van állítva: $(git remote get-url origin)"
    else
      say "A repo ${BOLD}publikus${RESET} lesz — így a bootstrap tokenmentes."
      note "Élesítéskor válik priváttá (15. döntés a DESIGN.md-ben)."
      if confirm "Létrehozzam a publikus InitInfra repót és pusholjam?"; then
        gh repo create InitInfra --public --source=. --remote=origin --push
      else
        SKIPPED+=("GitHub repo létrehozása")
      fi
    fi
    GH_OWNER=$(gh api user --jq .login 2>/dev/null || true)
    [[ -n "${GH_OWNER:-}" ]] && write_env GH_OWNER "$GH_OWNER"
  fi
fi

finish
